apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
  creationTimestamp: "2020-09-24T06:41:20Z"
  generation: 2
  labels:
    app: webapp
    deployment: green
  name: webapp-green
  namespace: default
  resourceVersion: "30702924"
  selfLink: /apis/apps/v1/namespaces/default/deployments/webapp-green
  uid: 7fe60e03-312c-4b19-a189-56ed4776a2ff
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: webapp
      deployment: green
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: webapp
        deployment: green
    spec:
      containers:
      - image: rraghur/flaskapp-env
        env:
          - name: MESSAGE
            value: "Hello K8s"
        imagePullPolicy: Always
        name: flaskapp-env
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
