apiVersion: v1
kind: Service
metadata:
  labels:
    app: webapp
  name: webapp
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: webapp
  sessionAffinity: None
  type: ClusterIP
