apiVersion: v1
kind: Service
metadata:
  labels:
    app: webapp
  name: webapp
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: webapp-green
    deployment: green
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
