apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: webapp-green
    deployment: green
  name: webapp-green
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webapp-green
      deployment: green
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: webapp-green
        deployment: green
    spec:
      containers:
      - image: rraghur/flaskapp-env
        env:
          - name: MESSAGE       # Upper case - what the app expects
            valueFrom:
              secretKeyRef:
                  name: webapp-secret
                  key: message  # Lower case - what's in the cm
        imagePullPolicy: Always
        name: flaskapp-env
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
